// <auto-generated />
using System;
using GoalKeepers.EntityFrameWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalKeepers.EntityFrameWork.Migrations
{
    [DbContext(typeof(GoalKeeperViewerDbContext))]
    partial class GoalKeeperViewerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoalKeepers.EntityFrameWork.DTOs.GoalKeeperViewerDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AttackingKeeper")
                        .HasColumnType("bit");

                    b.Property<bool>("Crosses")
                        .HasColumnType("bit");

                    b.Property<bool>("GoalLineKeeper")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodWithFeet")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reflexes")
                        .HasColumnType("bit");

                    b.Property<bool>("SweeperKeeper")
                        .HasColumnType("bit");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GoalKeeperViewers");
                });
#pragma warning restore 612, 618
        }
    }
}
